# Generated by Django 4.0 on 2024-06-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_alter_deposited_options_alter_gotochat_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposited',
            name='item2_1_document',
            field=models.FileField(null=True, upload_to='documents', verbose_name='Загрузка документа для пункта 2.1'),
        ),
        migrations.AlterField(
            model_name='deposited',
            name='item2_1_message',
            field=models.TextField(null=True, verbose_name='Текст сообщения для пункта 2.1'),
        ),
        migrations.AlterField(
            model_name='deposited',
            name='item2_1_reference',
            field=models.TextField(null=True, verbose_name='Ссылка для пункта 2.1'),
        ),
        migrations.AlterField(
            model_name='gotochat',
            name='message',
            field=models.TextField(null=True, verbose_name='Текст сообщения для пункта 4'),
        ),
        migrations.AlterField(
            model_name='gotochat',
            name='reference',
            field=models.TextField(null=True, verbose_name='Ссылка для пункта 4'),
        ),
        migrations.AlterField(
            model_name='kazahstancart',
            name='item1_2_document',
            field=models.FileField(null=True, upload_to='documents', verbose_name='Загрузка документа для пункта 1.2'),
        ),
        migrations.AlterField(
            model_name='kazahstancart',
            name='item1_2_message',
            field=models.TextField(null=True, verbose_name='Текст сообщения для пункта 1.2'),
        ),
        migrations.AlterField(
            model_name='kazahstancart',
            name='item1_2_reference',
            field=models.TextField(null=True, verbose_name='Ссылка для пунка 1.2'),
        ),
        migrations.AlterField(
            model_name='kazahstancart',
            name='item1_3_document',
            field=models.FileField(null=True, upload_to='documents', verbose_name='Загрузка документа для пункта 1.3'),
        ),
        migrations.AlterField(
            model_name='kazahstancart',
            name='item1_3_message',
            field=models.TextField(null=True, verbose_name='Текст сообщения для пункта 1.3'),
        ),
        migrations.AlterField(
            model_name='kazahstancart',
            name='item1_3_reference',
            field=models.TextField(null=True, verbose_name='Ссылка для пунка 1.3'),
        ),
        migrations.AlterField(
            model_name='openaccount',
            name='item3_1_document',
            field=models.FileField(null=True, upload_to='documents', verbose_name='Загрузка документа для пункта 3.1'),
        ),
        migrations.AlterField(
            model_name='openaccount',
            name='item3_1_message',
            field=models.TextField(null=True, verbose_name='Текст сообщения для пункта 3.1'),
        ),
        migrations.AlterField(
            model_name='openaccount',
            name='item3_1_reference',
            field=models.TextField(null=True, verbose_name='Ссылка для пункта 3.1'),
        ),
        migrations.AlterField(
            model_name='openaccount',
            name='item3_2_document',
            field=models.FileField(null=True, upload_to='documents', verbose_name='Загрузка документа для пункта 3.2'),
        ),
        migrations.AlterField(
            model_name='openaccount',
            name='item3_2_message',
            field=models.TextField(null=True, verbose_name='Текст сообщения для пункта 3.2'),
        ),
        migrations.AlterField(
            model_name='openaccount',
            name='item3_2_reference',
            field=models.TextField(null=True, verbose_name='Ссылка для пункта 3.2'),
        ),
        migrations.AlterField(
            model_name='usdt',
            name='message',
            field=models.TextField(null=True, verbose_name='Текст сообщения для пункта 5'),
        ),
        migrations.AlterField(
            model_name='usdt',
            name='reference',
            field=models.TextField(null=True, verbose_name='Ссылка для пункта 5'),
        ),
    ]
