# Generated by Django 4.0 on 2024-06-25 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_alter_deposited_item2_1_document_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KazahstanCart1_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item1_2_message', models.TextField(null=True, verbose_name='Текст сообщения для пункта 1.2')),
                ('item1_2_reference', models.TextField(null=True, verbose_name='Ссылка для пунка 1.2')),
                ('item1_2_document', models.FileField(null=True, upload_to='documents', verbose_name='Загрузка документа для пункта 1.2')),
            ],
            options={
                'verbose_name': 'Пункт 1.2 Карта Казахстана',
                'verbose_name_plural': 'Пункт 1.2 Карта Казахстана',
            },
        ),
        migrations.CreateModel(
            name='KazahstanCart1_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item1_3_message', models.TextField(null=True, verbose_name='Текст сообщения для пункта 1.3')),
                ('item1_3_reference', models.TextField(null=True, verbose_name='Ссылка для пунка 1.3')),
                ('item1_3_document', models.FileField(null=True, upload_to='documents', verbose_name='Загрузка документа для пункта 1.3')),
            ],
            options={
                'verbose_name': 'Пункт 1.3 Карта Казахстана',
                'verbose_name_plural': 'Пункт 1.3 Карта Казахстана',
            },
        ),
        migrations.CreateModel(
            name='OpenAccount3_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item3_1_message', models.TextField(null=True, verbose_name='Текст сообщения для пункта 3.1')),
                ('item3_1_reference', models.TextField(null=True, verbose_name='Ссылка для пункта 3.1')),
                ('item3_1_document', models.FileField(null=True, upload_to='documents', verbose_name='Загрузка документа для пункта 3.1')),
            ],
            options={
                'verbose_name': 'Пункт 3.1 Открытие счетов',
                'verbose_name_plural': 'Пункт 3.1 Открытие счетов',
            },
        ),
        migrations.CreateModel(
            name='OpenAccount3_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item3_2_message', models.TextField(null=True, verbose_name='Текст сообщения для пункта 3.2')),
                ('item3_2_reference', models.TextField(null=True, verbose_name='Ссылка для пункта 3.2')),
                ('item3_2_document', models.FileField(null=True, upload_to='documents', verbose_name='Загрузка документа для пункта 3.2')),
            ],
            options={
                'verbose_name': 'Пункт 3.2 Открытие счетов',
                'verbose_name_plural': 'Пункт 3.2 Открытие счетов',
            },
        ),
        migrations.DeleteModel(
            name='KazahstanCart',
        ),
        migrations.DeleteModel(
            name='OpenAccount',
        ),
        migrations.AlterModelOptions(
            name='deposited',
            options={'verbose_name': 'Пункт 2.1 Депозит', 'verbose_name_plural': 'Пункт 2.1 Депозит'},
        ),
    ]
