# Generated by Django 4.0 on 2024-06-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_kazahstancart1_2_kazahstancart1_3_openaccount3_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposited',
            name='item2_1_document_reserve',
            field=models.FileField(blank=True, null=True, upload_to='documents', verbose_name='Загрузка документа для пункта 2.1'),
        ),
        migrations.AddField(
            model_name='kazahstancart1_2',
            name='item1_2_document_reserve',
            field=models.FileField(blank=True, null=True, upload_to='documents', verbose_name='Загрузка документа для пункта 1.2'),
        ),
        migrations.AddField(
            model_name='kazahstancart1_3',
            name='item1_3_document_reserve',
            field=models.FileField(blank=True, null=True, upload_to='documents', verbose_name='Загрузка документа для пункта 1.3'),
        ),
        migrations.AddField(
            model_name='openaccount3_1',
            name='item3_1_document_reserve',
            field=models.FileField(blank=True, null=True, upload_to='documents', verbose_name='Загрузка документа для пункта 3.1'),
        ),
        migrations.AddField(
            model_name='openaccount3_2',
            name='item3_2_document_reserve',
            field=models.FileField(blank=True, null=True, upload_to='documents', verbose_name='Загрузка документа для пункта 3.2'),
        ),
        migrations.AlterField(
            model_name='deposited',
            name='item2_1_document',
            field=models.FileField(blank=True, null=True, upload_to='documents', verbose_name='Загрузка документа для пункта 2.1'),
        ),
        migrations.AlterField(
            model_name='deposited',
            name='item2_1_reference',
            field=models.TextField(blank=True, null=True, verbose_name='Ссылка для пункта 2.1'),
        ),
        migrations.AlterField(
            model_name='gotochat',
            name='reference',
            field=models.TextField(blank=True, null=True, verbose_name='Ссылка для пункта 4'),
        ),
        migrations.AlterField(
            model_name='kazahstancart1_2',
            name='item1_2_document',
            field=models.FileField(blank=True, null=True, upload_to='documents', verbose_name='Загрузка документа для пункта 1.2'),
        ),
        migrations.AlterField(
            model_name='kazahstancart1_2',
            name='item1_2_reference',
            field=models.TextField(blank=True, null=True, verbose_name='Ссылка для пунка 1.2'),
        ),
        migrations.AlterField(
            model_name='kazahstancart1_3',
            name='item1_3_document',
            field=models.FileField(blank=True, null=True, upload_to='documents', verbose_name='Загрузка документа для пункта 1.3'),
        ),
        migrations.AlterField(
            model_name='kazahstancart1_3',
            name='item1_3_reference',
            field=models.TextField(blank=True, null=True, verbose_name='Ссылка для пунка 1.3'),
        ),
        migrations.AlterField(
            model_name='openaccount3_1',
            name='item3_1_document',
            field=models.FileField(blank=True, null=True, upload_to='documents', verbose_name='Загрузка документа для пункта 3.1'),
        ),
        migrations.AlterField(
            model_name='openaccount3_1',
            name='item3_1_reference',
            field=models.TextField(blank=True, null=True, verbose_name='Ссылка для пункта 3.1'),
        ),
        migrations.AlterField(
            model_name='openaccount3_2',
            name='item3_2_document',
            field=models.FileField(blank=True, null=True, upload_to='documents', verbose_name='Загрузка документа для пункта 3.2'),
        ),
        migrations.AlterField(
            model_name='openaccount3_2',
            name='item3_2_reference',
            field=models.TextField(blank=True, null=True, verbose_name='Ссылка для пункта 3.2'),
        ),
        migrations.AlterField(
            model_name='usdt',
            name='reference',
            field=models.TextField(blank=True, null=True, verbose_name='Ссылка для пункта 5'),
        ),
    ]
